# Generated by Django 6.0.7 on 2026-08-05 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('legal_name', models.CharField(max_length=200)),
                ('business_type', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=100)),
                ('gst_number', models.CharField(max_length=20)),
                ('pan_number', models.CharField(max_length=20)),
                ('establishment_year', models.PositiveIntegerField()),
                ('industry', models.CharField(max_length=100)),
                ('products_services', models.TextField()),
                ('annual_turnover', models.DecimalField(decimal_places=2, max_digits=12)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VendorDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_certificate', models.FileField(upload_to='vendor_documents/')),
                ('gst_certificate', models.FileField(upload_to='vendor_documents/')),
                ('pan_document', models.FileField(upload_to='vendor_documents/')),
                ('bank_document', models.FileField(upload_to='vendor_documents/')),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='vendor_documents/')),
                ('other_document', models.FileField(blank=True, null=True, upload_to='vendor_documents/')),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.vendorregistration')),
            ],
        ),
        migrations.CreateModel(
            name='VendorContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_name', models.CharField(max_length=100)),
                ('primary_designation', models.CharField(max_length=100)),
                ('primary_email', models.EmailField(max_length=254)),
                ('primary_mobile', models.CharField(max_length=15)),
                ('primary_phone', models.CharField(blank=True, max_length=15)),
                ('secondary_name', models.CharField(blank=True, max_length=100)),
                ('secondary_designation', models.CharField(blank=True, max_length=100)),
                ('secondary_email', models.EmailField(blank=True, max_length=254)),
                ('secondary_mobile', models.CharField(blank=True, max_length=15)),
                ('secondary_phone', models.CharField(blank=True, max_length=15)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.vendorregistration')),
            ],
        ),
    ]
